catalog/urls.py
from django.urls import path
from catalog.views import (
    index,
    GenreListView,
    GenreDetailView,
    GenreUpdateView,
    ActorListView,
    ActorDetailView,
    ActorCreateView,
    ActorUpdateView,
    ActorDeleteView,
    MovieListView,
    MovieDetailView,
    MovieCreateView,
    MovieUpdateView,
    MovieDeleteView,
    UserCreateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("genres/", GenreListView.as_view(), name="genre-list"),
    path("genres/<int:pk>/", GenreDetailView.as_view(), name="genre-detail"),
    path("genres/<int:pk>/update/",
         GenreUpdateView.as_view(),
         name="genre-update"
         ),
    path("actors/", ActorListView.as_view(), name="actor-list"),
    path("actors/<int:pk>/", ActorDetailView.as_view(), name="actor-detail"),
    path("actors/create/", ActorCreateView.as_view(), name="actor-create"),
    path("actors/<int:pk>/update/",
         ActorUpdateView.as_view(),
         name="actor-update"
         ),
    path("actors/<int:pk>/delete/",
         ActorDeleteView.as_view(),
         name="actor-delete"
         ),
    path("movies/", MovieListView.as_view(), name="movie-list"),
    path("movies/<int:pk>/", MovieDetailView.as_view(), name="movie-detail"),
    path("movies/create/", MovieCreateView.as_view(), name="movie-create"),
    path("movies/<int:pk>/update/",
         MovieUpdateView.as_view(),
         name="movie-update"
         ),
    path("movies/<int:pk>/delete/",
         MovieDeleteView.as_view(),
         name="movie-delete"
         ),
    path("users/create/", UserCreateView.as_view(), name="user-create"),
]

app_name = "catalog"

friends_imdb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path('__debug__/', include('debug_toolbar.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
<footer class="footer pt-5 mt-5">
  <div class="pt-5">
    <div class="container">
      <div class="row d-flex justify-content-center">
        <div class="col-lg-5 ms-auto text-center">
          <h4 class="mb-1">Contact us:</h4>
        </div>
        <div class="d-flex col-lg-5 me-lg-auto my-lg-auto mt-5">
          <a href="https://t.me/rakamaka_phone" class="btn btn-info mb-0 me-2" target="_blank">
            <i class="fab fa-telegram me-1"></i> Telegram
          </a>
          <a href="https://www.facebook.com/oleksandrmamchur14" class="btn btn-primary mb-0 me-2" target="_blank">
            <i class="fab fa-facebook-square me-1"></i> Facebook
          </a>
          <a href="https://www.instagram.com/rakamakaphone1/?igshid=ZDdkNTZiNTM%3D" class="btn btn-dark mb-0 me-2" target="_blank">
            <i class="fab fa-instagram me-1"></i> Instagram
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-12">
    <div class="text-center">
      <p class="my-4 text-sm">
        Friends' IMDB by &copy; <a target="_blank" href="https://www.facebook.com/oleksandrmamchur14" target="_blank">Oleksandr Mamchur</a>
      </p>
    </div>
  </div>
</footer>

templates/includes/navigation.html
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid">
          <a class="navbar-brand font-weight-bolder ms-sm-3"
             href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
            Friends' IMDB
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                  Movies
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-1">
                </a>
                <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a href="{% url 'catalog:movie-list' %}" class="dropdown-item border-radius-md">
                      All Movies
                    </a>
                    <a href="#" class="dropdown-item border-radius-md">
                      Most Rated
                    </a>
                    <a href="#" class="dropdown-item border-radius-md">
                      Best Rating
                    </a>
                  </div>
                </div>
              </li>
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                  Actors
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-1">
                </a>
                <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a href="{% url 'catalog:actor-list' %}" class="dropdown-item border-radius-md">
                      All Actors
                    </a>
                  </div>
                </div>
              </li>
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                  Genres
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-1">
                </a>
                <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a href="{% url 'catalog:genre-list' %}" class="dropdown-item border-radius-md">
                      All Genres
                    </a>
                  </div>
                </div>
              </li>
              {% if user.is_authenticated %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" href="{% url 'logout' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Logout (User: {{ user.username }})</p>
                  </a>
                </li>
              {% else %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" href="{% url 'login' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Sign In</p>
                  </a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <div class="container top-5 mt-2" >
    <div class="row">
      <div class="col-12">
        <ul class="pagination pagination-primary">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}" aria-label="Previous">
              <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
            </a>
          </li>
          {% endif %}
          <li class="page-item active">
            <span class="page-link">{{ page_obj.number }}</span>
          </li>
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}" aria-label="Next">
              <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
{% endif %}

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

templates/includes/search.html
{% load crispy_forms_filters %}

<form action="" method="get" class="d-flex">
  {{ search_form|crispy }}

  <input type="submit" value="🔍" class="btn btn-light">
</form>