catalog/urls.py
from django.urls import path
from catalog.views import (
    index,
    GenreListView,
    GenreDetailView,
    GenreUpdateView,
    ActorListView,
    ActorDetailView,
    ActorCreateView,
    ActorUpdateView,
    ActorDeleteView,
    MovieListView,
    MovieDetailView,
    MovieCreateView,
    MovieUpdateView,
    MovieDeleteView,
    UserCreateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("genres/", GenreListView.as_view(), name="genre-list"),
    path("genres/<int:pk>/", GenreDetailView.as_view(), name="genre-detail"),
    path("genres/<int:pk>/update/",
         GenreUpdateView.as_view(),
         name="genre-update"
         ),
    path("actors/", ActorListView.as_view(), name="actor-list"),
    path("actors/<int:pk>/", ActorDetailView.as_view(), name="actor-detail"),
    path("actors/create/", ActorCreateView.as_view(), name="actor-create"),
    path("actors/<int:pk>/update/",
         ActorUpdateView.as_view(),
         name="actor-update"
         ),
    path("actors/<int:pk>/delete/",
         ActorDeleteView.as_view(),
         name="actor-delete"
         ),
    path("movies/", MovieListView.as_view(), name="movie-list"),
    path("movies/<int:pk>/", MovieDetailView.as_view(), name="movie-detail"),
    path("movies/create/", MovieCreateView.as_view(), name="movie-create"),
    path("movies/<int:pk>/update/",
         MovieUpdateView.as_view(),
         name="movie-update"
         ),
    path("movies/<int:pk>/delete/",
         MovieDeleteView.as_view(),
         name="movie-delete"
         ),
    path("users/create/", UserCreateView.as_view(), name="user-create"),
]

app_name = "catalog"

friends_imdb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path('__debug__/', include('debug_toolbar.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    class Meta:
        ordering = ("username",)


class Genre(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ("name",)

    def __str__(self) -> str:
        return self.name


class Actor(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    class Meta:
        ordering = ("last_name",)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"


class Movie(models.Model):
    title = models.CharField(max_length=255, unique=True)
    year = models.IntegerField()
    description = models.TextField(blank=True)
    genres = models.ManyToManyField(Genre, related_name="movies")
    actors = models.ManyToManyField(Actor, blank=True, related_name="movies")

    class Meta:
        ordering = ("year",)

    def __str__(self) -> str:
        return f"{self.title} ({self.year})"


class Rating(models.Model):
    movie = models.ForeignKey(
        Movie,
        on_delete=models.CASCADE,
        related_name="ratings"
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="ratings"
    )
    rating = models.IntegerField(null=True)

catalog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import MinValueValidator

from catalog.models import Movie, User, Genre, Actor, Rating


class MovieForm(forms.ModelForm):
    min_year = 1930
    year = forms.IntegerField(
        required=True,
        validators=[MinValueValidator(min_year)]
    )
    genres = forms.ModelMultipleChoiceField(
        queryset=Genre.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    actors = forms.ModelMultipleChoiceField(
        queryset=Actor.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Movie
        fields = "__all__"


class MovieSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by title or year"}
        ),
    )


class ImdbUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email"
        )


class ActorSearchForm(forms.Form):
    last_name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        ),
    )


class RatingForm(forms.ModelForm):
    rating = forms.IntegerField(
        min_value=1,
        max_value=10,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Write your rating"}
        ),
    )

    class Meta:
        model = Rating
        exclude = ["movie", "user"]

catalog/views.py
from django.contrib.auth import get_user
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet, Q, Avg
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from catalog.forms import (
    ActorSearchForm,
    MovieForm,
    MovieSearchForm,
    ImdbUserCreationForm,
    RatingForm,
)
from catalog.models import Movie, Actor, Genre, User, Rating


def index(request: HttpRequest) -> HttpResponse:
    num_movies = Movie.objects.count()
    num_actors = Actor.objects.count()
    num_users = User.objects.count()
    last_added = Movie.objects.all().order_by("-id")[:3]
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_movies": num_movies,
        "num_actors": num_actors,
        "num_users": num_users,
        "num_visits": num_visits + 1,
        "last_added": last_added,
    }
    return render(request, "catalog/index.html", context=context)


class GenreListView(generic.ListView):
    model = Genre
    queryset = Genre.objects.prefetch_related("movies")
    template_name = "catalog/genre_list.html"
    context_object_name = "genre_list"


class GenreDetailView(generic.DetailView):
    model = Genre


class GenreUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Genre
    fields = "__all__"
    template_name = "catalog/genre_form.html"
    success_url = reverse_lazy("catalog:genre-list")


class ActorListView(generic.ListView):
    model = Actor
    template_name = "catalog/actor_list.html"
    context_object_name = "actor_list"
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(ActorListView, self).get_context_data(**kwargs)

        context["search_form"] = ActorSearchForm

        return context

    def get_queryset(self) -> QuerySet:
        queryset = Actor.objects.prefetch_related("movies")
        form = ActorSearchForm(self.request.GET)

        if form.is_valid():
            query = Q(last_name__icontains=form.cleaned_data["last_name"]) | Q(
                first_name__icontains=form.cleaned_data["last_name"]
            )
            return queryset.filter(query)
        return queryset


class ActorDetailView(generic.DetailView):
    model = Actor


class ActorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Actor
    fields = "__all__"
    success_url = reverse_lazy("catalog:actor-list")


class ActorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Actor
    fields = "__all__"

    def get_success_url(self) -> HttpResponse:
        return reverse("catalog:actor-detail", args=[self.object.pk])


class ActorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Actor
    fields = "__all__"
    template_name = "catalog/actor_confirm_delete.html"
    success_url = reverse_lazy("catalog:actor-list")


class MovieListView(generic.ListView):
    model = Movie
    template_name = "catalog/movie_list.html"
    context_object_name = "movie_list"
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(MovieListView, self).get_context_data(**kwargs)

        context["search_form"] = MovieSearchForm

        return context

    def get_queryset(self) -> QuerySet:
        queryset = Movie.objects.prefetch_related("genres")
        form = MovieSearchForm(self.request.GET)

        if form.is_valid():
            query = Q(title__icontains=form.cleaned_data["title"]) | Q(
                year__icontains=form.cleaned_data["title"]
            )
            return queryset.filter(query)
        return queryset


class MovieDetailView(generic.DetailView):
    model = Movie

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context["genre_list"] = self.object.genres.all()
        context["form"] = RatingForm()
        avg_rating = self.object.ratings.aggregate(Avg("rating"))
        if avg_rating["rating__avg"]:
            context["avg_rating"] = round(avg_rating["rating__avg"], 1)
        if self.request.user.is_authenticated:
            user = get_user(self.request)
            rating = Rating.objects.filter(
                user=user,
                movie=self.object
            ).first()
            rate = rating.rating if rating else None
            context["rating"] = rate
        return context

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        form = RatingForm(request.POST)
        if form.is_valid():
            movie = Movie.objects.get(pk=kwargs.get("pk"))
            rating, created = Rating.objects.get_or_create(
                movie=movie, user=request.user
            )
            if created or "rating" in form.changed_data:
                rating.rating = form.cleaned_data["rating"]
                rating.save()
            return HttpResponseRedirect(
                reverse("catalog:movie-detail", args=[kwargs.get("pk")])
            )


class MovieCreateView(LoginRequiredMixin, generic.CreateView):
    model = Movie
    form_class = MovieForm
    success_url = reverse_lazy("catalog:movie-list")


class MovieUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Movie
    form_class = MovieForm

    def get_success_url(self) -> HttpResponse:
        return reverse("catalog:movie-detail", args=[self.object.pk])


class MovieDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Movie
    fields = "__all__"
    template_name = "catalog/movie_confirm_delete.html"
    success_url = reverse_lazy("catalog:movie-list")


class UserCreateView(generic.CreateView):
    model = User
    form_class = ImdbUserCreationForm
    success_url = reverse_lazy("login")

templates/catalog/actor_confirm_delete.html
{% extends "base-presentation.html" %}

{% block content %}
  <div class="container top-5 mt-7" >
    <div class="row">
      <div class="col-12">
        <h1>Delete Actor</h1>
        <br>
        <p>Are you sure, that you want to delete the actor: {{ actor }}</p>
        <br>
        <form action="" method="post">
          {% csrf_token %}

          <input type="submit" value="Yes, delete" class="btn btn-danger">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/actor_detail.html
{% extends "base-presentation.html" %}

{% block content %}
  <div class="container top-5 mt-7" >
    <div class="row">
      <div class="col-12">
        <div class="d-flex justify-content-between">
          <h3 class="mr-auto">Actor: {{ actor.first_name }} {{ actor.last_name }}</h3>
          <div class="ml-auto">
            <a href="{% url 'catalog:actor-update' pk=actor.id %}" class="btn btn-secondary link-to-page mr-2">
              Update
            </a>
            <a href="{% url 'catalog:actor-delete' pk=actor.id %}" class="btn btn-danger link-to-page">
              Delete
            </a>
          </div>
        </div>
        <h5>Filmography:</h5>
        <ul>
          {% for movie in actor.movies.all %}
          <li>
            <a href="{% url 'catalog:movie-detail' pk=movie.id %}">{{ movie }}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/actor_form.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container top-5 mt-7" >
    <div class="row">
      <div class="col-4">
        <h1>{{ object|yesno:"Update, Create" }} Actor</h1>
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}
          <input class="btn btn-primary" type="submit" value="Submit">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/actor_list.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container top-5 mt-7" >
    <div class="row">
      <div class="col-12">
        <div class="d-flex justify-content-between align-items-center">
          <h1 class="m-0">Actors:</h1>

          <a href="{% url 'catalog:actor-create' %}" class="btn btn-primary ml-auto">
            Create
          </a>
        </div>
        {% block search %}
          {% include "includes/search.html" %}
        {% endblock %}
        <ul>
          {% for actor in actor_list %}
            <li>
              <a href="{% url 'catalog:actor-detail' pk=actor.id %}">{{ actor }}</a>
               ({{ actor.movies.count }} movie{{ actor.movies.count|pluralize }})
            </li>
          {% endfor %}
        </ul>

      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/genre_detail.html
{% extends "base-presentation.html" %}


{% block content %}
  <div class="container top-5 mt-7" >
    <div class="row">
      <div class="col-12">
        <div class="d-flex justify-content-between">
          <h3 class="mr-auto">Genre: {{ genre.name }}</h3>
          <div class="ml-auto">
            <a href="{% url 'catalog:genre-update' pk=genre.id %}" class="btn btn-secondary link-to-page ml-2">
              Update
            </a>
          </div>
        </div>
        <h5>Movies:</h5>
        <ul>
          {% for movie in genre.movies.all %}
          <li>
            <a href="{% url 'catalog:movie-detail' pk=movie.id %}">{{ movie }}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/genre_form.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div class="container top-5 mt-7" >
    <div class="row">
      <div class="col-4">
        <h1>Update Genre</h1>
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}
          <input class="btn btn-primary" type="submit" value="Submit">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/genre_list.html
{% extends "base-presentation.html" %}


{% block content %}
  <div class="container top-5 mt-7" >
    <div class="row">
      <div class="col-12">
        <h1>Genres:</h1>
        <ul>
          {% for genre in genre_list %}
            <li><a href="{% url 'catalog:genre-detail' pk=genre.id %}">{{ genre.name }}</a>
              ({{ genre.movies.count }} movie{{ genre.movies.count|pluralize }})
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/index.html
{% extends "base-presentation.html" %}


{% block title %} Home Page {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}
  <header class="header-2">
    <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/vid.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">Friends' Movie Data Base</h1>
            <p class="lead text-white mt-3">
              The place where you can share your opinion
              <br>
              Made by <a class="text-white" target="_blank" href="https://www.instagram.com/rakamakaphone1/?igshid=ZDdkNTZiNTM%3D" target="_blank">Me :)</a>
            </p>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <a href="{% url 'catalog:movie-list' %}">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1" countTo="{{ num_movies }}">0</span>+</h1>
                <h5 class="mt-3">Movies</h5>
              </div>
              <hr class="vertical dark">
              </a>
            </div>
            <div class="col-md-4 position-relative">
              <a href="{% url 'catalog:actor-list' %}">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"> <span id="state2" countTo="{{ num_actors }}">0</span>+</h1>
                <h5 class="mt-3">Actors</h5>
              </div>
              <hr class="vertical dark">
              </a>
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"> <span id="state3" countTo="{{ num_users }}">0</span>+</h1>
                <h5 class="mt-3">Active users</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="py-5">
    <div class="container">
      <div class="row">
        <div class="row text-center mt-5">
          <div class="col-lg-6 mx-auto">
            <h2 class="text-primary text-gradient mb-0">Last added movies:</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="row d-flex flex-wrap justify-content-center">
      {% for movie in last_added %}
        <div class="col-md-2">
          <a href="{% url 'catalog:movie-detail' pk=movie.id %}">
            <div class="mt-2 ms-2">
              <h6 class="mb-0">{{ movie }}</h6>
            </div>
            <div class="card move-on-hover">
              <img class="w-100" src="{{ ASSETS_ROOT }}/img/movies/{{ movie.id }}.jpg" alt="">
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </section>
  <section class="py-sm-7" id="download-soft-ui">
    <div class="container">
      <div class="row">
        <div class="col-6 mx-auto">
          <div class="text-center">
            <h3 class="mt-5 mb-4">Used these technologies</h3>
            <div class="row justify-content-center">
              <div class="col-lg-2 col-4">
                <img src="{{ ASSETS_ROOT }}/img/logos/medium-logos/python_logo.png" class="img-fluid opacity-6" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Python">
              </div>
              <div class="col-lg-2 col-4">
                <img src="{{ ASSETS_ROOT }}/img/logos/medium-logos/django_logo.png" class="img-fluid opacity-6" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Django">
              </div>
              <div class="col-lg-2 col-4">
                <img src="{{ ASSETS_ROOT }}/img/logos/medium-logos/bootstrap_logo.png" class="img-fluid" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Bootstrap 5">
              </div>
              <div class="col-lg-2 col-4">
                  <img src="{{ ASSETS_ROOT }}/img/logos/medium-logos/html_logo.png" class="img-fluid" data-bs-toggle="tooltip" data-bs-placement="bottom" title="HTML">
              </div>
              <div class="col-lg-2 col-4">
                  <img src="{{ ASSETS_ROOT }}/img/logos/medium-logos/css_logo.png" class="img-fluid" data-bs-toggle="tooltip" data-bs-placement="bottom" title="CSS">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>

{% endblock javascripts %}

templates/catalog/movie_confirm_delete.html
{% extends "base-presentation.html" %}


{% block content %}
  <div class="container top-5 mt-7" >
    <div class="row">
      <div class="col-12">
        <h1>Delete Movie</h1>
        <br>
        <p>Are you sure, that you want to delete the actor: {{ movie }}</p>
        <br>
        <form action="" method="post">
          {% csrf_token %}

          <input type="submit" value="Yes, delete" class="btn btn-danger">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/movie_detail.html
{% extends "base-presentation.html" %}


{% block content %}
  <div class="container top-5 mt-7" >
    <div class="row">
      <div class="col-12">
        <div class="d-flex justify-content-between">
          <h3 class="mr-auto">Movie: {{ movie.title }}</h3>
          <div class="ml-auto">
            <a href="{% url 'catalog:movie-update' pk=movie.id %}" class="btn btn-secondary link-to-page ml-2">
              Update
            </a>
            <a href="{% url 'catalog:movie-delete' pk=movie.id %}" class="btn btn-danger link-to-page ml-2">
              Delete
            </a>
          </div>
        </div>
        <h6>Release year: {{ movie.year }}</h6>
        <h6>Rating: {{ avg_rating }} / 10</h6>
        <h6>Genres:
          {% for genre in genre_list %}
            <a href="{% url 'catalog:genre-detail' pk=genre.id %}">{{ genre.name }}</a>
          {% endfor %}
        </h6>
        <div class="col-md-2 card move-on-hover">
          <img class="w-100" src="{{ ASSETS_ROOT }}/img/movies/{{ movie.id }}.jpg" alt="">
        </div>
        <br>
          {% if user.is_authenticated %}
            {% if rating %}
              <h6>Your rating: {{ rating }}</h6>
              <form action="{% url 'catalog:movie-detail' pk=movie.id %}" method="post" class="form-inline custom-form">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-primary custom-btn" type="submit" value="Change Rating">
              </form>
            {% else %}
              <form action="{% url 'catalog:movie-detail' pk=movie.id %}" method="post" class="form-inline custom-form">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-primary custom-btn" type="submit" value="Rate">
              </form>
            {% endif %}
          {% else %}
            <p><a href="{% url 'login' %}" class="btn btn-info">Rate movie</a></p>
          {% endif %}


        <h6>Cast:</h6>
        <ul>
          {% for actor in movie.actors.all %}
            <li>
              <a href="{% url 'catalog:actor-detail' pk=actor.id %}">{{ actor.first_name }} {{ actor.last_name }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/movie_form.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div class="container top-5 mt-7" >
    <div class="row">
      <div class="col-4">
        <h1>{{ object|yesno:"Update, Create" }} Movie</h1>
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}
          <input class="btn btn-primary" type="submit" value="Submit">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/movie_list.html
{% extends "base-presentation.html" %}


{% block content %}
  <div class="container top-5 mt-7" >
    <div class="row">
      <div class="col-12">
        <div class="d-flex justify-content-between align-items-center">
          <h1 class="m-0">Movies:</h1>

          <a href="{% url 'catalog:movie-create' %}" class="btn btn-primary ml-auto">
            Create
          </a>
        </div>
        {% block search %}
          {% include "includes/search.html" %}
        {% endblock %}
        <ul>
          {% for movie in movie_list %}
            <li><a href="{% url 'catalog:movie-detail' pk=movie.id %}">{{ movie }}</a>
              {% for genre in movie.genres.all %}
                {{  genre.name  }}
              {% endfor %}
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}